version: "3"

services:
  web:
    container_name: "storyteller-frontend"
    build:
      context: ./storytellerFrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./storytellerFrontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - "./storytellerFrontend/.env.production"
  server:
    container_name: "storyteller-backend"
    hostname: "storyteller-backend"
    build:
      context: ./storytellerBackend/storyteller
      dockerfile: Dockerfile
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://storyteller-db:5432/storyteller
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: "postgres"
    hostname: "storyteller-db"
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: storyteller
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - dbvolumes:/var/lib/postgresql/data

volumes:
  dbvolumes:
